version=0.1

[default.deploy.parameters]
stack_name = "minecraft-lambda"
s3_bucket = "nnsk-minecraft-bucket"
s3_prefix = "creeper"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

